// ReSharper disable All 

// This file was automatically generated by the Dapper.Database T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name:       `ConnectionStrings:ContactApp`
//     Provider:                     `System.Data.SqlClient`
//     Connection String:            `Server=(localdb)\mssqllocaldb;Database=ContactApp;Trusted_Connection=True;`
//     Include Views:                `False`
//     Include IncludeRelationships: `True`

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Dapper.Database.Attributes;

namespace ContactApp.Models
{

    /// <summary>
    ///     A class which represents the Contact table.
    /// </summary>
    [Table("Contact", Schema = "dbo")]
    [Serializable]
    public partial class Contact
    {

        [Column] [Key] public virtual Guid Id { get; set; }

        [Column] [Required] [StringLength(64)] public virtual string FirstName { get; set; }

        [Column] [Required] [StringLength(64)] public virtual string LastName { get; set; }

        [Column] [DatabaseGenerated(DatabaseGeneratedOption.Computed)] public virtual string FullName { get; set; }

        [Column] [StringLength(64)] public virtual string Company { get; set; }

        [Column] [StringLength(64)] public virtual string Title { get; set; }

        [Column] [StringLength(256)] public virtual string Email { get; set; }

        [Column] [IgnoreUpdate] public virtual DateTime CreatedOn { get; set; }

        [Column] public virtual DateTime? UpdatedOn { get; set; }

        [Column] [Timestamp] public virtual byte[] Timestamp { get; set; }

        [Ignore] public virtual IEnumerable<Phone> Phones { get; set; }
    }

    /// <summary>
    ///     A class which represents the Phone table.
    /// </summary>
    [Table("Phone", Schema = "dbo")]
    [Serializable]
    public partial class Phone
    {

        [Column] [Key] public virtual Guid Id { get; set; }

        [Column] public virtual Guid ContactId { get; set; }

        [Column] [Required] [StringLength(32)] public virtual string Number { get; set; }

        [Column] [StringLength(8)] public virtual string Label { get; set; }

        [Column] public virtual int Ordinal { get; set; }

        [Column] [IgnoreUpdate] public virtual DateTime CreatedOn { get; set; }

        [Column] public virtual DateTime? UpdatedOn { get; set; }

        [Ignore] public virtual Contact Contact { get; set; }
    }
}

// ReSharper restore All
